[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "The high-frequency MRI database"
authors = [{name = "GIN/SCIL", email = "lpetit8@gmail.com"}]
dynamic = ["version", "description"]
